const mapCells = [new MapCell(1, 0, materials[5]), new MapCell(2, 0, materials[2]), new MapCell(3, 0, materials[2]), new MapCell(4, 0, materials[3]), new MapCell(8, 0, materials[3]), new MapCell(13, 0, materials[1]), new MapCell(14, 0, materials[1]),
                  new MapCell(3, 1, materials[4]), new MapCell(2, 1, materials[1]), new MapCell(8, 1, materials[2]), new MapCell(11, 1, materials[3]), new MapCell(14, 1, materials[4]),
                  new MapCell(0, 2, materials[2]), new MapCell(4, 2, materials[1]), new MapCell(8, 2, materials[5]), new MapCell(10, 2, materials[2]),
                  new MapCell(1, 3, materials[4]), new MapCell(7, 3, materials[2]), new MapCell(11, 3, materials[4]), new MapCell(15, 3, materials[5]),
                  new MapCell(0, 4, materials[3]), new MapCell(5, 4, materials[1]), new MapCell(6, 4, materials[5]), new MapCell(9, 4, materials[1]), new MapCell(10, 4, materials[5]), new MapCell(13, 4, materials[3]),
                  new MapCell(0, 5, materials[5]), new MapCell(1, 5, materials[1]), new MapCell(2, 5, materials[3]), new MapCell(7, 5, materials[1]), new MapCell(8 , 5, materials[1]), new MapCell(13, 5, materials[3]), new MapCell(14, 5, materials[2]),  new MapCell(15, 5, materials[1]),
                  new MapCell(1, 6, materials[1]),
                  new MapCell(4, 7, materials[4]), new MapCell(5, 7, materials[5]), new MapCell(8, 7, materials[3]), new MapCell(11, 7, materials[1]),
                  new MapCell(2, 8, materials[2]), new MapCell(5, 8, materials[5]), new MapCell(13, 8, materials[5]), new MapCell(14, 8, materials[4]),
                  new MapCell(2, 9, materials[3]), new MapCell(3, 9, materials[1]), new MapCell(9, 9, materials[4]), new MapCell(10, 9, materials[2]), new MapCell(11, 9, materials[2]), new MapCell(13, 9, materials[1]),
                  new MapCell(1, 10, materials[4]), new MapCell(6, 10, materials[1]), new MapCell(7, 10, materials[1]), new MapCell(8, 10, materials[1]), new MapCell(14, 10, materials[5]),
                  new MapCell(6, 11, materials[1]), new MapCell(8, 11, materials[1]), new MapCell(11, 11, materials[1]), new MapCell(14, 11, materials[3]),
                ];
